name: take_home
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^8.1.3
  cached_network_image: ^3.3.1
  chopper: ^8.0.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  injectable: ^2.4.1
  get_it: ^7.7.0
  logger: ^2.3.0
  flutter_bloc: ^8.1.5
  google_fonts: ^6.2.1
  fpdart: ^1.1.0
  freezed: ^2.5.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  collection: ^1.18.0
  json_annotation: ^4.9.0
  carousel_slider: ^4.2.1
  http: ^1.2.1
  uuid: ^4.4.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  auto_route_generator: ^8.0.0
  chopper_generator: ^8.0.0
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  flutter_gen_runner:

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  output: lib/core/gen/
  line_length: 150
